server:
  port: 1001


spring:
  application:
    name: eureka-server


# eureka禁止自身的客户端的注册行为
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false


